name: Build e Publicacao de imagem Docker

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar Codigo
        uses: actions/checkout@v4

      - name: Configurar o Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Autenticar no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extrair Metadados do Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/minha-aplicacao
          tags: |
            type=raw,value=latest
            type=sha,format=short

      - name: Construir e Publicar imagem
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Ativa o cache nativo do Docker para evitar re-fazer o npm install do zero toda vez:
          cache-from: type=gha
          cache-to: type=gha,mode=max
